### ISSUE TITLE
Peer killed - restarting in 10 seconds

### ISSUE THREAD

**Issue by sbolten** [pfandfrei/Homegear-Xiaomi-Smarthome#1]
Homegear version 0.6.20-987
Gateway Firmware: 1.4.1_149.0143

Devices: 1 Gateway + 1 Temp&Hum Sensor
Working in MI Home App

Hi, followed your installation script and succeeded partially. Devices were recognized successfully after I added fhe following to MiCube.php:

include_once 'MiBaseDevice.php';

Have the following devices:

(Family)> ls
      ID │ Name                      │ Serial Number │ Type │ Type String
─────────┼───────────────────────────┼───────────────┼──────┼───────────────────────────
         │                           │               │      │
       3 │                           │    MI008D3B77 │ 286C │                 MiCentral
       4 │                           │    MI01823A4F │ 288C │                MiSensorHT
─────────┴───────────────────────────┴───────────────┴──────┴───────────────────────────

Subscribing to mqtt I cann see Illumination events occuring for peer 3 - nothing for peer 4.

homegear.err shows:

09/08/17 09:25:14.138 Module Miscellaneous: Error: Script of peer 3 was killed. Restarting in 10 seconds...                                                                                                
09/08/17 09:25:29.638 Module Miscellaneous: Error: Script of peer 3 was killed. Restarting in 10 seconds...                                                                                                
09/08/17 09:25:44.718 Module Miscellaneous: Error: Script of peer 3 was killed. Restarting in 10 seconds...                                                                                                
09/08/17 09:25:59.809 Module Miscellaneous: Error: Script of peer 3 was killed. Restarting in 10 seconds...                                                                                                
09/08/17 09:26:15.104 Module Miscellaneous: Error: Script of peer 3 was killed. Restarting in 10 seconds...                         

mihome.log:

2017-09-08 09:26:15 >>  {"cmd":"read_ack","model":"gateway","sid":"34ce008d3b77","short_id":0,"data":"{\"rgb\":1023442175,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}                             
2017-09-08 09:26:30 >>  {"cmd": "read", "sid":"34ce008d3b77"}                                                                                                                                              
2017-09-08 09:26:30 >>  {"cmd":"read_ack","model":"gateway","sid":"34ce008d3b77","short_id":0,"data":"{\"rgb\":1023442175,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}                             
2017-09-08 09:26:45 >>  {"cmd": "read", "sid":"34ce008d3b77"}                                                                                                                                              
2017-09-08 09:26:45 >>  {"cmd":"read_ack","model":"gateway","sid":"34ce008d3b77","short_id":0,"data":"{\"rgb\":1023442175,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}               

So it looks like in general it is working but somewhere it crashes.

Regards,

Stephan

**Comment by pfandfrei** [comment]
There was an incompatibility to Homegear < 0.7.x. It seems there was a signature change for putParamset( ) from v0.6.x to v0.7.x in Homegear. I fixed it by not using putParamset( ) for older versions. So some information is not stored (e.g. proto_version).
I should work now, but I recommend to update Homegear to version 0.7.x

**Comment by pfandfrei** [comment]
solved with 0.4.4

**Comment by sbolten** [comment]
Hi, thx Upgraded homegear to 0.7 installed again - now its working without errors. Best S.

**Comment by sbolten** [comment]
Hi, thx for the fixes. Working smoothly now. Could not find out how to set params (ie Gateway light or rgb) through mqtt. Would appreciate if you could give me a hint.

Best, Stephan

⁣Gesendet mit BlueMail ​

**Comment by pfandfrei** [comment]
This is easy. Let's say your MiGateway has peer id 48. To change the color of the light just publish the decimal value for the rgb color to
`<prefix>/<homegearId>/set/48/1/RGB`
and then publish true to switch light on (false to switch off) to
`<prefix>/<homegearId>/set/48/1/ENABLE`

The prefix and homegearId are defined in mqtt.conf.
See Homegear documentation at https://doc.homegear.eu/data/homegear/communication_protocols.html#mqtt

**Comment by sbolten** [comment]
Thx. Will try it later. Best Stephan

⁣Gesendet mit BlueMail ​

**Comment by pfandfrei** [comment]
Forget to mention: You have to publish a value>0 for the brightness (values from 0-100 are allowed).

`<prefix>/<homegearId>/set/48/1/BRIGHTNESS`
