### ISSUE TITLE
Mehrere Gateways sind nicht möglich

### ISSUE THREAD

**Issue by pfandfrei** [pfandfrei/Homegear-Xiaomi-Smarthome#3]
Der Betrieb mit mehreren Gateways führt zu vollgespammten Logs und permanenten Neustarts der Scripts.

**Comment by ibcsim** [comment]
Hallo Frank,

vielen Dank für dein Engagement!
Bitte melde dich, wenn ich etwas tun kann um deine Entwicklung zu unterstützen. 

bis dahin viele Grüße,
Simon

**Comment by pfandfrei** [comment]
OK, noch ein schneller Versuch (mehr Zeit habe ich gerade nicht):
Nimm bitte den Stand von hier und ändere in der MiGateway.xml Zeile 13 von 
`        <startType>permanent</startType>`
in
`        <startType>once</startType>`
Mit dem aktuellen Stand gibt es dann genau einen Eintrag "unable to bind ..." und es sollte hoffentlich laufen.

**Comment by ibcsim** [comment]
Sodele, eben wieder dazu gekommen zu testen.
Es schaut ganz gut aus ;-) Die reports vom zweiten Gateway kommen noch über Zeile 241 $this->error_log($json); im MiCentral.php und damit wird der Gerätestatus nicht upgedated. Ansonsten kann man das Script nun wieder dauerhaft laufen lassen :-)

[20181028_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522628/20181028_archiv.tar.gz)

[edit1]: Falls das relevant wäre: die unknown Nachrichten kommen nicht immer vom selben Gateway. Ich vermute, dass nach dem Scriptstart einfach das Gateway, welches als zweites seinen Heartbeat sendet in die Ungunst des Scripts fällt.?

[edit2]: Nach dem einmaligen Listen aller Geräte im mihome.log beim Startvorgang kommen gerade weder heartbeats noch reports. Ich kann nicht mehr reproduzieren, wie vorhin noch reports kamen. Jetzt kommt jedenfalls mit <startType>once</startType> gar nichts mehr.

**Comment by pfandfrei** [comment]
Bitte checke noch mal den aktuellen Stand 0.6.3 aus. Es sieht so aus, als ob irgendwas das Script zum Abbruch bringt. Dadurch, dass das Script mit "once" und nicht mehr mit "permanent" gestartet wurde, hat es sich wohl beendet, wodurch Du keine Updates mehr bekommst.
Das liegt vermutlich am "MiMagnet", weil ich da noch einen Fehler in der Kanalliste hatte.
Der letzte Eintrag in der mihome.log bezog sich übrigens auch auf den MiMagnet. Wundert mich nur, dass sonst nirgendwo ein Fehler gelistet ist.

**Comment by ibcsim** [comment]
Es ist wie gehabt: nach dem erstmaligen Durchlauf kommen keine Einträge mehr im Log.

[20181018_1255_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522743/20181018_1255_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Das Script wird mit Fehlercode -32500 beendet. Laut Homegear Dokumentation gibt es diesen Fehlercode nur für setData( ), updateFirmware( ) und setSystemVariable( ). Die verwende ich aber nicht.
Ich habe noch ein paar Stellen mit Fehlerbehandlung versehen. Probier mal ob wir damit einen aussagekräftigen Hinweis bekommen.
Bitte master auschecken, hab keinen Tag vergeben.

**Comment by ibcsim** [comment]
Die Logs scheinen gar nicht mehr Informationen zu enthalten.?

[20181018_1503_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522829/20181018_1503_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Langsam wird's komisch. Bist Du sicher, dass auch die XML Dateien auf Stand sind?
Kommentiere mal die Zeile 387 (`$hg->setValue($this->_peerId, 0, 'HEARTBEAT', time());`) in der MiGateway.php aus

**Comment by ibcsim** [comment]
So, habe nochmal /etc/homegear/devices/254/* und /var/lib/homegear/scripts/DeviceScripts/Xiaomi/* geleert und mit den aktuellen Dateien befüllt. Schaut für mich gleich aus.?

[20181028_1553_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522867/20181028_1553_archiv.tar.gz)

und hier mit Zeile 387 auskommentiert:
[20181028_1558_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522868/20181028_1558_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Sorry, ist gerade ein Stochern im Dunkeln. Bei mir läuft es aber auch mit Homegear 0.7, aber das wird  es wohl nicht sein.
Kann Du mal auf Debuglevel 5 erhöhen und den Log schicken? Es scheint immer beim ersten Heartbeat vom Gateway auszusteigen.

**Comment by ibcsim** [comment]
tadaaa:

[20181028_1618_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522899/20181028_1618_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Hat mir leider nichts gebracht. Ich hab noch einen ErrorHandler eingefügt. Kannst Du wieder die aktuelle Version auschecken? Der Fehler isr damit nicht weg, aber evtl gibt es jetzt einen Hinweis

**Comment by ibcsim** [comment]
viel Erfolg :-)

[20181028_1754_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2522978/20181028_1754_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Das verwirrt mich noch mehr weil hier Geräte als UNKNOWN auftauchen und das Script nicht mit Fehlercode beendet wurde. Ich muss noch ein wenig mehr Logging drumherum bauen. Heute und morgen wird das aber definitiv nichts mehr, aber ich bleibe dran ...

**Comment by ibcsim** [comment]
Alles klar, immer mit der Ruhe ;-) vielen Dank nochmal für dein Engagement!

**Comment by pfandfrei** [comment]
Hallo Simon,

wenn Du noch mal testen magst ... bitte Version 0.6.4 auschecken.
Ich konnte mir ein Szenario erstellen, das wie bei Dir abstürzt. Nach den Änderungen ist das behoben. Außerdem habe ich das Logging verbessert.

Gruß,
Frank

**Comment by ibcsim** [comment]
moin Frank,

danke für das Update! Das schaut in der Tat nach einer maßgeblichen Verbesserung aus :-) 
Was mir noch auffällt: Nachrichten von den Tochtergeräten (egal welches Gateway) stehen im Log als UNKNOWN, obwohl deren Status korrekt interpretiert wird. 

Noch eine andere Frage: der Variablenstatus beim Start (read & read_ack) wird an Homegear übergeben, richtig? Sonst müsste nämlich gewartet werden, bis alle Fensterkontakte ihren Heartbeat abgesetzt haben um sicher sagen zu können, dass alle Fenster geschlossen sind.?

[20181101_0708_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2537414/20181101_0708_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Beim Logging der Tochtergeräte ist mir da tatsächlich was durchgerutscht. Wird voraussichtlich heute Abend gefixt. 
Bei Starten werden alle Geräte aus den Gateways gelesen und die Werte entsprechend gesetzt. Das soll heißen: So lange der Gateway weiß, welchen Status der Fensterkontakt hat, wird er auch bei Start übermittelt und im Gerät gesetzt.
Edit: Da ist noch ein weiterer Fehler, wodurch vermutlich keine Parameter von außen gesetzt werden können => Auch heute Abend ...

**Comment by pfandfrei** [comment]
nächster Versuch: 0.6.5

**Comment by ibcsim** [comment]
Danke Frank, es scheint gefixed zu sein :-) Konnte zumindest keinen Fehler mehr feststellen. Vielen Dank für deinen super Support!!

[20181101_2246_archiv.tar.gz](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/2540336/20181101_2246_archiv.tar.gz)

**Comment by pfandfrei** [comment]
Ja, sieht gut aus. Ebenfalls danke für Deine gute Unterstützung.
