### ISSUE TITLE
Batteriespannung wird nicht an Homegear übergeben

### ISSUE THREAD

**Issue by ibcsim** [pfandfrei/Homegear-Xiaomi-Smarthome#6]
Hello again Frank :-)

bei der heutigen Einrichtung einer Batteriespannungsüberwachung für die Xiaomi-Geräte ist mir aufgefallen, dass die payload des Knotens für die Spannung in Homegear stets 0 enthält. Im mihome.log werden die Spannungen jedoch richtig befüllt, für mich sieht die Formatierung aber nicht ganz korrekt aus.?

`{"cmd":"heartbeat","model":"magnet","sid":"158d000234e470","short_id":51077,"data":"{\"voltage\":3015,\"status\":\"open\"}"}`

Wie siehst du das?
Viele Grüße, Simon

**Comment by pfandfrei** [comment]
Hallo Simon,

Das kann ich nach Prüfung bedingt bestätigen. Die Spannung wird schon in den Kanal geschrieben aber außerdem wird komischerweise zuvor eine 0 geschrieben. Warum das so ist weiß ich nicht, vielleicht eine Besonderheit bei Channel 0. 

Mit Debuglevel 5 sieht das dann in homegear.log wie folgt aus:
1. Schreibe PRESSURE auf Channel 1 (richtig):

```

11/13/18 20:19:40.528 Script Engine Server: Info: Client number 0 is calling RPC method: setValue
(Integer) 7
(Integer) 1
(String) PRESSURE
(Float) 986
11/13/18 20:19:40.529 MQTT Client: Debug: queueMessage(peerId, channel, keys, values) -> peerId=7, channel=1, keys, values
11/13/18 20:19:40.529 MQTT Client: Debug: queueMessage (message) topic: plain/7/1/PRESSURE message:986

```

=> Ein mal queueMessage nach setValue mit dem Wert

2. Schreibe VOLTAGE auf Channel 0 (falsch):

```
11/13/18 20:18:35.738 Script Engine Server: Info: Client number 0 is calling RPC method: setValue
(Integer) 8
(Integer) 0
(String) VOLTAGE
(Integer) 3025
11/13/18 20:18:35.738 MQTT Client: Debug: queueMessage(peerId, channel, keys, values) -> peerId=8, channel=0, keys, values
11/13/18 20:18:35.738 MQTT Client: Debug: queueMessage (message) topic: plain/8/0/VOLTAGE message:0
11/13/18 20:18:35.738 MQTT Client: Debug: queueMessage(peerId, channel, keys, values) -> peerId=8, channel=0, keys, values
11/13/18 20:18:35.738 MQTT Client: Debug: queueMessage (message) topic: plain/8/0/VOLTAGE message:3025
```

Du siehst, dass nach dem setValue zwei mal queueMessage erscheinen, zuerst mit dem Wert 0. Warum weiß ich nicht ... ich werd mal im Homegear Forum fragen ...

Gruß,
Frank

**Comment by ibcsim** [comment]
Hey Frank,

Sathya hat sich das eben mal angesehen und gemeint er hat hier tatsächlich etwas verändert, kann das aber auf die Schnelle nicht bearbeiten. Er will das mal noch bei Gelegenheit debuggen.

Grüße, Simon
