### ISSUE TITLE
homegear 0.8 Support?

### ISSUE THREAD

**Issue by sbolten** [pfandfrei/Homegear-Xiaomi-Smarthome#7]
Hallo,

aktualisiere gerade meine Smarthome Komponenten auf den neusten Stand. Integration Xoaomi mit homegear funktioniert derzeit wunderbar mit homegear 0.7x. im Readme steht, dass v0.7 supported ist. Wie steht es um 0.8? Möchte mir nix kaputt machen.

Gruss, Stephan

**Comment by pfandfrei** [comment]
Ich habe bei mir nur eine Version 0.7 am aktiv und allgemein eigentlich immer die letzte stable Version. Gerade gestern habe ich wegen issue #6 eine Version 0.8 angetestet und es sollte grundsätzlich laufen. Allerdings kann ich hier keine Erfahrungen zu irgendwelchen Langzeittests berichten.

**Comment by ibcsim** [comment]
Bei mir läuft die 0.8.0-2380 und ich habe damit keine Probleme hinsichtlich Stabilität. Der letzte Neustart war vor drei Wochen, von daher läuft ;-)

**Comment by sbolten** [comment]
Danke.... Update auf homegear 0.8x durchgeführt - scheint alles zu funktionieren :)
