### ISSUE TITLE
Nach Update keine laufenden Gerätestatus mehr.?

### ISSUE THREAD

**Issue by ibcsim** [pfandfrei/Homegear-Xiaomi-Smarthome#9]
Hey Frank,

bei mir sind wieder ein paar Geräte dazu gekommen, sodass ich nun das dritte Gateway hinzufügen wollte. Da das nicht auf Anhieb geklappt hat, habe ich auch von deinen Scripten die aktuellen Versionen auf den RasPi kopiert und damit probiert. Im mihome.log stehen nun lediglich die Status aller Geräte vom initialen Startup, es kommen danach keine weiteren Statusmeldungen/heardbeats. Es wurden auch lediglich die zwei bislang bekannten Gateways erkannt. 
Die mihome.err spuckt aus: `[EXCEPTION] /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiBaseDevice.php line 38(-5 Unknown parameter.)`
Hast du da eine Idee? Was kann ich dir liefern? Liegt es womöglich an mir?

Vielen Dank und viele Grüße,
Simon

**Comment by pfandfrei** [comment]
Hallo Simon,

es sieht so aus als ob da eine Gerätedefinition falsch ist. Scheinbar aber ein Gerät, das ich nicht besitze. Ich habe gerade mal das Logging etwas verbessert, damit sollten wir rauskriegen, wo der Fehler liegt. Bitte aktuellste Version testen und nochmals die Zeile aus mihome.err posten.

Gruß,
Frank

**Comment by ibcsim** [comment]
Guten Morgen Frank,

das Errorlog zeigt leider keine Veränderung. Habe die exception weiterhin drei Mal drin stehen mit dem selben Text.

Grüße, Simon

**Comment by pfandfrei** [comment]
OK, nächster Versuch. Die Meldung in mihome.err wird gleich bleiben, dafür brauche ich aber noch die letzten Zeilen der mihome.log, wenn Du die letztere Änderung getestet hast.

**Comment by ibcsim** [comment]
Hier habe ich dir die letzten Zeilen aus der mihome.log:

`2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d0002b5d120"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d0002b5d120","short_id":32113,"data":"{\"voltage\":2965,\"lux\":\"176\"}"}
2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d0001ae964f"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"motion","sid":"158d0001ae964f","short_id":34313,"data":"{\"voltage\":2965}"}
2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d0002b6efc6"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d0002b6efc6","short_id":39103,"data":"{\"voltage\":2985,\"lux\":\"668\"}"}
2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d000258654a"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"plug","sid":"158d000258654a","short_id":1165,"data":"{\"voltage\":3600,\"status\":\"off\",\"inuse\":\"0\",\"power_consumed\":\"661\",\"load_power\":\"0.00\"}"}
2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d00028d0bd0"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"plug","sid":"158d00028d0bd0","short_id":25344,"data":"{\"voltage\":3600,\"status\":\"off\",\"inuse\":\"0\",\"power_consumed\":\"160068\",\"load_power\":\"0.00\"}"}
2019-12-30 11:56:34 >>  {"cmd": "read", "sid":"158d000257fb1d"}
2019-12-30 11:56:34 >>  {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d000257fb1d","short_id":15470,"data":"{\"voltage\":2965,\"lux\":\"881\"}"}
2019-12-30 11:56:34 >>  {"cmd":"heartbeat","model":"gateway","sid":"7811dcb279c1","short_id":"0","token":"BP7Aqp36i9iT8LmD","data":"{\"ip\":\"192.168.178.42\"}"}`

Kannst du da was rauslesen?

**Comment by pfandfrei** [comment]
Das könnte interessant werden: Laut der mir bekannten Dokumentation (die schon recht alt ist), liefert der 'plug' keinen Datenpunkt 'voltage', dafür aber 'load_voltage'. Der Log sagt aber etwas anderes. Ich hab noch ein paar kleine Änderungen gemacht. Bitte testen und ggf mihome.err/mihome.log (letzte Zeilen reichen) posten.

**Comment by ibcsim** [comment]
Interessant ist gut ;-)
mihome.log:
`2019-12-30 12:28:22 >>  {"cmd": "read", "sid":"158d000257fb1d"}
2019-12-30 12:28:22 >>  {"cmd":"read_ack","model":"sensor_motion.aq2","sid":"158d000257fb1d","short_id":15470,"data":"{\"voltage\":2965,\"lux\":\"881\"}"}
2019-12-30 12:28:22 >>  {"cmd":"heartbeat","model":"gateway","sid":"7811dcb279c1","short_id":"0","token":"CbvxrtrctwCIy8Ta","data":"{\"ip\":\"192.168.178.42\"}"}`

mihome.err:
`2019-12-30 12:28:21 [EXCEPTION] /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiBaseDevice.php line 38(-5 Unknown parameter.|plug )
2019-12-30 12:28:22 [EXCEPTION] /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiBaseDevice.php line 38(-5 Unknown parameter.|plug )
2019-12-30 12:28:22 [EXCEPTION] /var/lib/homegear/scripts/DeviceScripts/Xiaomi/MiBaseDevice.php line 38(-5 Unknown parameter.|plug )`

**Comment by pfandfrei** [comment]
Noch ein paar kleine Änderungen, da ich beim letzten Fix etwas übereilig war. Bitte Homegear stoppen, mihome.err und mihome.log löschen. Dann wieder starten und beide Dateien hier posten.
Ich bin aber der Meinung, dass es eigentlich laufen müsste, außer dass mihome.err vollgespamt wird. Dafür denke ich mir was aus, wenn ich sicher bin die Ursache gefunden zu haben

**Comment by ibcsim** [comment]
sodele, hier die Logs:
[mihome.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4009864/mihome.log)
[mihome.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4009865/mihome.err.log)

das errorlog bleibt (nach den exceptions beim startup) leer, scheint irgendwo zu hängen.?
vielen Dank dir schon mal ;-)

**Comment by pfandfrei** [comment]
Hmm, so wie das aussieht würde ich erwarten, dass alles läuft. Im errorlog gibt es erst wieder eine Meldung, wenn der Plug sich meldet, der debuglog müsste weiter gefüllt werden

**Comment by ibcsim** [comment]
Vom Plug kommen i.d.R alle 10s Rückmeldungen. In beide Logs wurde seit dem Startup nichts mehr geschrieben.

**Comment by pfandfrei** [comment]
Dann bitte noch die homegear-scriptengine.err und evtl auch homegear.err. Ich hoffe da ist noch ein Fehler zu finden.
Ich hab hier produktiv ein Homegear 0.7 und ein frisch aufgesetztes Homegear 0.8 laufen. Beide ohne Fehler aber ohne Plug

**Comment by ibcsim** [comment]
Bei mir läuft 0.8.0-2771. Ein alter Stand deiner Scripte läuft auch einwandfrei (auch mit den Plugs). Erst seit dem Update geht's nicht mehr :-)
Hier die (abgespeckten) Logs:

[homegear-scriptengine.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4009941/homegear-scriptengine.err.log)
[homegear.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4009942/homegear.err.log)

Das Interessanteste dürfte sein:
`12/30/19 12:28:22.393 Script Engine Server: Critical: Client process with pid 16200 was killed with signal 11.`

**Comment by pfandfrei** [comment]
Ja, das ist der Knackpunkt. Das Script wird beendet und daher passiert dann auch nichts mehr im Log. Warum das so ist weiß ich momentan nicht. Aber es hat sicher etwas mit den mehreren Gateways zu tun. Ich erinnere mich, dass wir diesbezüglich schon mal Probleme hatten.
Bin momentan noch ein wenig ratlos, aber ich überlege mir etwas. Ich glaube ich muss mir mal einen zweiten Gateway zulegen ...
EDIT: Ist denn die Homegear Version gleich geblieben oder hast Du die auch aktualiseirt?

**Comment by ibcsim** [comment]
Das Verhalten konnte ich schon bei einer älteren Homegearversion feststellen. Homegear aktualisiere ich immer wieder mal, bislang hat sich dadurch in Verbindung mit Xiaomi kaum etwas verschlimmbessert ;-).
Soll ich dir eine Leihgabe zukommen lassen, oder hast du auch Verwendung dafür?

**Comment by pfandfrei** [comment]
Ich habe einen neuen Branch 'testing' aufgemacht. Da gibt es ein paar Änderungen, die seit der Version mit den mehreren Gateways rausgeflogen sind. Willst Du nochmal testen?
EIne Leihgabe bringt mir nur bedingt etwas. Ich würde mir den zur Seite legen, um bei strukturellen Änderungen oder bei gemeldeten Fehlern testen zu können.

**Comment by ibcsim** [comment]
Yeehaw, es kommen wieder Status!!! Auch das mihome.err Log bleibt leer. Allerdings wirft homegear neue Medlungen aus:

[homegear-scriptengine.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4010758/homegear-scriptengine.err.log)
[homegear.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4010770/homegear.err.log)

Außerdem wurde laut Log ein core-file erzeugt^^.

**Comment by pfandfrei** [comment]
Das core File ist evtl aus den vorherigen Versuchen. Du kannst es ja mal löschen.
Hab noch einen kleinen Fehler behoben ...

**Comment by ibcsim** [comment]
jetzt sind es nur noch zwei:
[homegear-scriptengine.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4010820/homegear-scriptengine.err.log)

(und das dritte Gateway im Netzwerk taucht halt nicht auf)

**Comment by pfandfrei** [comment]
Hast Du das core File vorher gelöscht?
Bist Du sicher, dass der dritte Gateway im Developer Modus ist? Im mihome.log müssten sich dann auch 3 Gateways melden. Im letzten Log waren es nur 2:
```

2019-12-30 14:17:15 >>  {"cmd":"whois"}
2019-12-30 14:17:15 >>  {"cmd":"iam","port":"9898","sid":"7811dcb267e3","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.21"}
2019-12-30 14:17:15 >>  {"cmd":"iam","port":"9898","sid":"7811dcb279c1","model":"gateway","proto_version":"1.1.2","ip":"192.168.178.42"}

```

**Comment by ibcsim** [comment]
Das core-file hab ich gelöscht, ja. Ob vor dem Update auf das aktuelle testing oder nicht, bin ich mir nicht mehr sicher. Das dritte Gateway ist im dev-mode, ja. Im mihome.log stehen immer nur die ersten Zwei.
Das Dritte müsste mit der ip 192.168.178.56 auftauchen.
GW 192.168.178.21: V272 1.4.1_164 MW300 Model:lumi.gateway.v3
GW 192.168.178.42: V272 1.4.1_164 MW300 Model:lumi.gateway.v3
GW 192.168.178.56: V272 1.4.1_175 MW300 Model:lumi.gateway.v3

**Comment by pfandfrei** [comment]
Bzgl des core Files: Dann evtl löschen, Homegear neu starten und während es läuft prüfen, ob ein core File existiert. Evtl entsteht das erst beim (unsauberen) Beenden des Xiaomi Scripts. Wenn ich das richtig sehe, gibt es ja keine Meldung wie:

`Script Engine Server: Critical: Client process with pid 16200 was killed with signal 11`

mehr im Log.
Was passiert wenn die anderen zwei Gateways nicht am Strom sind?

**Comment by ibcsim** [comment]
Es wurde kein core-file mehr erzeugt, habe homegear nochmal neu gestartet. Das homegear.err Log enthält aktuell nur noch ein paar RPC Warnungen. Auch im scriptengine.err stehen nur die Warnungen aus https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/issues/9#issuecomment-569776205
Was mir eben auffällt: das dritte GW beschwert sich in der App, über eine hohe Paketverlustrate, obwohl es direkt neben dem AP steht. Vielleicht ist das ja sogar im Eimer.

Mit GW1 und GW2 offline bleibt mihome.log bei whois stehen und im scriptengine.err stehen die zwei Meldungen von https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/issues/9#issuecomment-569776205 erneut drin.
homegear.err wirft keine neuen Fehler.

**Comment by pfandfrei** [comment]
Im Moment denke ich, das ich da nichts machen kann. Du könntest den Timeout für das anfängliche Discover erhöhen. Das ist in MiSmartHome.php Zeile 53. Aber mit den hohen Paketverlusten tust Du Dir vermutlich keinen Gefallen damit.
Vielleicht verlegst Du den Gateway mal woanders hin, etwas weiter weg.

**Comment by ibcsim** [comment]
Habe nun ein paar Steckdosen durch, jetzt ist die Paketverlustrate im Rahmen. Discovered wird es trotzdem nicht :-( 
Zeile 53 enthält kein timeout ;-) meinst du die MiCentral.php?
Auch mit 15s Timeout kommt kein GW3.

**Comment by ibcsim** [comment]
Aber interessant: das GW mit der IP 192.168.178.42 kommt nun zwei Mal:
[mihome.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4011040/mihome.log)

**Comment by pfandfrei** [comment]
Ja natürlich MiCentral.php. Hab's extra nachgeschaut und doch falsch gemacht.
Wenn sich nix meldet (mihome.log), kann ich leider nichts tun.
Vielleicht solltest Du den Gateway noch mal komplett resetten und neu einrichten. Ggf andere IP vergeben. Dafür hab ich aber keinen logischen Grund.
Der dritte GW hat ne neuere Firmwareversion als die anderen. Die läuft aber bei mir problemlos ...

**Comment by ibcsim** [comment]
Dass die 192.168.178.42 beim Discover zwei Mal kommt ist in Ordnung?

**Comment by pfandfrei** [comment]
Eigentlich nicht. Der dritte Gateway sollte sich aber auf jeden Fall alleine melden, was er ja nicht tut. Daher tippe ich momentan auf einen Fehler bei Deinem Gerät oder Netzwerk.
Mein Gateway "beschwert" sich übrigens auch über zu viele Paketverluste. Ist also wohl eher ein Standardproblem des Gateways

**Comment by ibcsim** [comment]
Hm, okay. Dann schau ich da mal weiter :-) Vielen Dank für deine Mühen und einen guten Rutsch!!

**Comment by pfandfrei** [comment]
Danke, ebenso. Solltest Du neue Erkenntnisse haben, melde Dich ruhig ...

**Comment by ibcsim** [comment]
Hey Frank,

habe nun dem dritten Gateway einen eigenen 2.4GHz Zugangspunkt ohne Mesh geschaffen -> Paketverlustrate 0%. Beim discover wird das dritte GW weiterhin nicht gelistet, allerdings steht nun ein neuer Fehler im Log:

[mihome.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4021937/mihome.log)
[mihome.err.log](https://github.com/pfandfrei/Homegear-Xiaomi-Smarthome/files/4021936/mihome.err.log)

Nach einem Neustart von homegear ist der Fehler wieder weg und lässt sich auch nicht mehr provozieren :-(
Weitere Beobachtung: es kam nun zwei Mal vor, dass bei einem discover per DeviceScripts/Xiaomi/MiSmartHome.php nur Geräte von einem der zwei bereits laufenden Gateways gelistet werden.

Sagt das irgendetwas aus oder eher nicht?

**Comment by pfandfrei** [comment]
Hallo Simon,

es sieht so aus als ob sich hier einer der Gateways nicht innerhalb des Timeouts von 5 sec gemeldet hat. Ich habe mal eingebaut, dass unbekannte Gateways automatisch nachträglich inklusive ihrer Geräte hinzugefügt werden.
Wenn sich Dein dritter Gateway aber überhaupt nicht meldet, kann ich da wenig dran machen. Evtl macht es Sinn, dass Du mal per Wireshark prüfst, ob der dritte Gateway überhaupt etwas auf Port 9898 sendet (oder vielleicht einen anderen Port benutzt).

Gruß,
Frank

PS: Mein zwiter Gateway ist bestellt, dauert aber noch ein wenig bis er da ist ...

**Comment by ibcsim** [comment]
yeehaw!!! Danke für den Tip mit Wireshark! Bin gar nicht darauf gekommen das mal mit zu sniffen^^. Auf 9898 kam tatsächlich gar nichts. Deshalb hab ich mal angefangen zu recherchieren: es gibt eine ganze Reihe von Leuten, die mit dieser Hardwareversion keine Meldungen mehr auf 9898 bekommen. Lösung [hier](https://community.openhab.org/t/solved-openhab2-xiaomi-mi-gateway-does-not-respond/52963/114) bzw. [hier](https://community.openhab.org/t/solved-openhab2-xiaomi-mi-gateway-does-not-respond/52963/171).
Auch wenn die ausgelesenen Parameter von allen Gateways die Selben waren, so scheinen sie sich doch zu unterscheiden -> zu erkennen an der Beschriftung auf der Rückseite (Kreisrund, dann erst LAN-Kommunikation aktivieren vor dem FW-Update -> siehe [hier](https://community.openhab.org/t/solved-openhab2-xiaomi-mi-gateway-does-not-respond/52963/153) )

Jetzt funzt es erstmal bis auf Weiteres ;-)

**Comment by pfandfrei** [comment]
Gut, dann schließe ich das mal hier. Neue Version mit Tag 0.7.2
